# Generated by Django 5.0.4 on 2024-05-05 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='upblish',
            new_name='publish',
        ),
    ]
